### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by raheebwa**
## Project Highlights
- [x] Implemented the styling of the different components based on the design
## New Tools
- [x] Node SASS

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @ Team :clap: 

### This is so great, you have really done it all :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this milestone :+1: just a one-issue left to work on............ :slightly_smiling_face: 
 
Let's work on the following;
**1. Kindly working on responsiveness, that's is; mobile view; 

image


**_Screenshot from pathwright below:_**
They want it to be fast, **dynamic and responsive to their actions** and therefore you decided to build it with React & Redux

image

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896712/

**[Optional]**
_category dropdown menu seems too long, kindly keep it short and it would be nice if we could click the `category` afterward the dropdown should appear._


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by raheebwa** [comment]
## Changes made
* Added responsiveness for media queries of max 768

**Comment by raheebwa** [comment]
aaqq

**Comment by shshamim63** [comment]
## Status :100: Approved
___
Hi Team,
You have covered all the mentioned issues, so nothing is blocking me to approve it.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Review by damiecode — COMMENTED** [review]
Project Approved

**Pull request merged**
